[package]
name = "rs09"
version = "0.1.0"
authors = ["Thomas Brupbacher <thomas.brupbacher@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha256 = "1.0.2"
regex = "1.4.5"
rayon = "1.5.1"
